NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('allauth.urls')),
    path("accounts/", include("accounts.urls")),
    path('news/', include('news.urls')),
]

NewsPaper/accounts/urls.py
from django.urls import path
from .views import SignUp

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
]

NewsPaper/news/urls.py
from django.urls import path
from . import views


urlpatterns = [
   path('', views.PostList.as_view(), name='post_list'),
   path('<int:pk>', views.PostDetail.as_view(), name='post_detail'),
   path('search/', views.PostSearch.as_view(), name='post_search'),

   path('news/create/', views.PostCreate.as_view(), name='new_create'),
   path('news/<int:pk>/update/', views.PostUpdate.as_view(), name='new_update'),
   path('news/<int:pk>/delete/', views.PostDelete.as_view(), name='new_delete'),

   path('articles/create/', views.PostCreate.as_view(), name='article_create'),
   path('articles/<int:pk>/update/', views.PostUpdate.as_view(), name='article_update'),
   path('articles/<int:pk>/delete/', views.PostDelete.as_view(), name='article_delete'),
]

NewsPaper/accounts/models.py
from django.db import models

# Create your models here.

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.urls import reverse


class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        posts_rating = self.posts.aggregate(pr=Coalesce(Sum('rating'), 0)).get('pr')
        comments_rating = self.author.comments.aggregate(cr=Coalesce(Sum('rating'), 0)).get('cr')
        post_comment_rating = self.posts.aggregate(pcr=Coalesce(Sum('rating'), 0)).get('pcr')
        print(posts_rating)
        print('------------------')
        print(comments_rating)
        print('------------------')
        print(post_comment_rating)

        self.rating = posts_rating * 3 + comments_rating + post_comment_rating
        self.save()


class Category(models.Model):
    tag = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.tag


article = 'AR'
news = 'NE'

GENRE = [
    (article, 'Статья'),
    (news, 'Новость'),
]


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    genre = models.CharField(max_length=2, choices=GENRE, default=news)
    post_time_in = models.DateTimeField(auto_now_add=True)
    post_category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    text_comment = models.TextField()
    comment_time_in = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPaper/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )


class CustomSignupForm(SignupForm):
    def save(self, request):
        user = super().save(request)
        common_users = Group.objects.get(name="authors")
        user.groups.add(common_users)
        return user

NewsPaper/news/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'text',
            'post_category',
            'author',
        ]

NewsPaper/accounts/views.py
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from .forms import SignUpForm


class SignUp(CreateView):
    model = User
    form_class = SignUpForm
    success_url = '/accounts/login'
    template_name = 'registration/signup.html'

NewsPaper/news/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from .models import Post
from datetime import datetime
from .filters import PostFilter
from .forms import PostForm


class PostList(ListView):
    model = Post
    ordering = 'post_time_in'
    template_name = 'posts.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        context['filterset'] = self.filterset
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'


class PostSearch(ListView):
    model = Post
    ordering = 'post_time_in'
    template_name = 'search.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class PostCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        if self.request.path == '/news/articles/create/':
            post.genre = 'AR'
        post.save()
        return super().form_valid(form)


class PostUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'


class PostDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('news.delete_post',)
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')

NewsPaper/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h1>{{ post.title|censor }}</h1>
<h2>{{ post.post_time_in|date:'d M Y' }}</h2>
<hr>
<h3>{{ post.text|censor }}</h3>

{% endblock content %}

NewsPaper/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Пост</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}

    <h1></h1>
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>

    <h1>Все посты</h1>
    <h3>{% current_time '%b %d %Y' %}</h3>
    <h3>Количество постов: {{paginator.count}}</h3>

    <hr>
        {% if perms.news.add_post %}
        <a href="{% url 'new_create' %}">Добавить новость</a>
        <a href="{% url 'article_create' %}">Добавить статью</a>
        {% endif %}
    {% if posts %}
        <table align = 'center'>
            <tr>
                <td><b>Заголовок</b></td>
                <td><b>Дата публикации</b></td>
                <td><b>Содержание</b></td>
                <td><b>Категория</b></td>
                {% if perms.news.change_post or perms.news.delete_post %}
                <td><b>Действия</b></td>
                {% endif %}
            </tr>
            {% for post in posts %}
            <tr>
                <td>{{ post.title|censor }}</td>
                <td>{{ post.post_time_in|date:'d M Y' }}</td>
                <td>{{ post.text|truncatechars:20|censor }}</td>
                <td>{{ post.get_genre_display }}</td>
                <td>
                    {% if perms.news.change_post %}
                    <a href="{% url 'new_update' pk=post.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a href="{% url 'new_delete' post.id %}">Удалить</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Постов нет!</h2>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
            ...
        <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

NewsPaper/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}

    <h1></h1>
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>

    <h1>Поиск постов</h1>
    <h3>{% current_time '%b %d %Y' %}</h3>
    <h3>Количество постов: {{ paginator.count }}</h3>

    <hr>
    {% if posts %}
        <table align = 'center'>
            <tr>
                <td>Заголовок</td>
                <td>Дата публикации</td>
                <td>Сожержание</td>
                <td>Категория</td>
            </tr>
            {% for post in posts %}
            <tr>
                <td>{{ post.title|censor }}</td>
                <td>{{ post.post_time_in|date:'d M Y' }}</td>
                <td>{{ post.text|truncatechars:20|censor }}</td>
                <td>{{ post.get_genre_display }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Постов нет!</h2>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
            ...
        <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}